<?php
require_once 'config.php';
session_start();
if (!isset($_SESSION['admin_logged']) || $_SESSION['admin_logged'] !== true) {
    die('Unauthorized');
}

header('Content-Type: application/sql');
header('Content-Disposition: attachment; filename="backup_' . date('Y-m-d_H-i-s') . '.sql"');

$output = "-- MySQL dump\n";
$output .= "-- Generated by Konverter Excel to MySQL\n";
$output .= "-- Date: " . date('Y-m-d H:i:s') . "\n\n";
$output .= "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
$output .= "START TRANSACTION;\n";
$output .= "SET time_zone = \"+00:00\";\n\n";

$tables = ['buku', 'log_konversi', 'admin'];

foreach ($tables as $table) {
    // Struktur
    $stmt = $pdo->query("SHOW CREATE TABLE `$table`");
    $row = $stmt->fetch(PDO::FETCH_ASSOC);
    $output .= "--\n-- Table structure for table `$table`\n--\n";
    $output .= "DROP TABLE IF EXISTS `$table`;\n";
    $output .= $row['Create Table'] . ";\n\n";
    
    // Data
    $stmtData = $pdo->query("SELECT * FROM `$table`");
    $rows = $stmtData->fetchAll(PDO::FETCH_ASSOC);
    if (count($rows) > 0) {
        $output .= "--\n-- Dumping data for table `$table`\n--\n";
        foreach ($rows as $rowData) {
            $columns = array_keys($rowData);
            $escapedValues = array_map(function($value) use ($pdo) {
                if ($value === null) return 'NULL';
                return $pdo->quote($value);
            }, array_values($rowData));
            $output .= "INSERT INTO `$table` (`" . implode("`, `", $columns) . "`) VALUES (" . implode(", ", $escapedValues) . ");\n";
        }
        $output .= "\n";
    }
}
$output .= "COMMIT;\n";
echo $output;